### PR TITLE
Implemented section 3 of the event page and added routing

### PR DESCRIPTION
**Pull request by Julia-yossa**
Hello , I have implemented section 3 of the event page. i have encountered some challenges. 
1-  The required image was not available in the assets. 
2- I added the pages to APP.js for visualisation and later on deleted the tags there awaiting for the event page where it belongs.
i am awaiting feedback. regards

### CODE REVIEW

**Comment by Julia-yossa** [comment]
Hello.

**Comment by Julia-yossa** [comment]
Hello, today is the last day of the challenge and this is my 4th pull request. Please can someone check my work and permit me to complete the challenge. That will be awesome. Thanks.

**Comment by alicendeh** [comment]
Merged👍

**Comment by Julia-yossa** [comment]
Thanks

**Pull request merged**
