### PR TITLE
Second Section created for Community Building

### PR DESCRIPTION
**Pull request by Angelvicks**
Hello @alicendeh I just finished with the issue https://github.com/wtm-buea/WTM-official-website/issues/16 , please review my pull requests and how can I ameliorate it?

### CODE REVIEW

**Comment by Angelvicks** [comment]
Please for that one, the path is from my computer, I think you just have to put your own path where the picture for the second section is located. I could not use the general form of putting paths in react.

**Comment by alicendeh** [comment]
Hello @Angelvicks you have to access the path correctly 
 so anyone who pulls won't have to change the code.
Check the previous code others did and see how they access the path.
If you have any difficulties get to me.

**Comment by alicendeh** [comment]
And you weren't supposed to merge. Only the project maintainers have the right to merge

**Comment by Angelvicks** [comment]
Sorry about the merge it was an accident. I updated the path like others did already so I think it can work on your machine now.

**Pull request closed without merging**
